repos:
  - repo: https://github.com/grantjenks/blue.git
    rev: v0.9.1
    hooks:
    - id: blue
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--sp pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
